# Generated by Django 5.1.4 on 2025-04-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequesthistory',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequesthistory',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequesthistory',
            name='time_elapsed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apirequesthistory',
            name='body_type',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='apirequesthistory',
            name='url',
            field=models.URLField(),
        ),
    ]
